/* Auto-generated by tiled2c.py -- DO NOT EDIT */
#ifndef MAP_DATA_H
#define MAP_DATA_H

#include <stdint.h>
#include <stdbool.h>
#include "gamelib.h"

/* === Map metadata === */
#define MAP_WIDTH        30
#define MAP_HEIGHT       20
#define MAP_TILE_WIDTH   32
#define MAP_TILE_HEIGHT  32

/* tileset "tilemap" */
#define MAP_TILESET_TILEMAP_FIRSTGID  0
#define MAP_TILESET_TILEMAP_TILECOUNT  598
#define MAP_TILESET_TILEMAP_COLUMNS    46

/* === Layer data === */
extern const int16_t map_layer_layer_0_base[MAP_WIDTH * MAP_HEIGHT];
extern const int16_t map_layer_layer_1[MAP_WIDTH * MAP_HEIGHT];

/* === Tile property bitmasks/arrays === */
extern const uint32_t tileprop_obstacle[19];
#define TILEPROP_OBSTACLE_EXISTS  1
#define TILEPROP_OBSTACLE_WORDS   19
#define TILE_HAS_OBSTACLE(tile_idx)  ((tileprop_obstacle[(tile_idx) >> 5] >> ((tile_idx) & 0x1F)) & 1)

/* === Object layer data === */
extern const map_obj_t map_obj_slime[5];
#define MAP_OBJ_SLIME_COUNT  5

#endif /* MAP_DATA_H */
